### ISSUE TITLE
How to obtain similarity scores from pssim?

### ISSUE THREAD

**Issue by Creling** [mmspg/pointssim#1]
Hi,

`[pssim] = pointssim(sA, sB, PARAMS)` returns a struct containing the following fields: 
```
normBA: [2×1 double]
normAB: [2×1 double]
normSym: [2×1 double]
curvBA: [2×1 double]
curvAB: [2×1 double]
curvSym: [2×1 double]
```

How to get the similarity scores from these fields?

Yours,

Creling

**Comment by Valexiou** [comment]
Hi, 

Each of the scores contained in the struct fields are similarity scores.  
For example, `normBA` returns two similarity scores, one for `Var` and one for `Mean` (if you are using the default configuration), which are computed after comparing normal vectors between `A` and `B`, by setting `A` as the reference.
Similarly for the rest.

I hope this is clear.
